### ISSUE TITLE
Improve hourly email subject and table title

### ISSUE THREAD

**Issue by taldcroft** [sot/jobwatch#10]
Can we change 
`2015: Week 09, Errs on test: ['ACE.h5', 'hrc_shield.h5', 'GOES_X.h5']` 
to 
`2015 Week 09 errors: ACE.h5, hrc_shield.h5, GOES_X.h5`

and:
`Hourly Job Status: 2015:066:14:50:04.876`
to something like
`Hourly Status: 2015:066 14:50Z (Mar 8, 09:50 EST)`

**Comment by jeanconn** [comment]
Closed by 3ece123ab6eec2db5e666ba951b96cf65883d677 and 87b57ee8e794296e5a732bafa6761c38d27593af
